CREATE DATABASE IF NOT EXISTS dsa_manager;
USE dsa_manager;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS folders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  is_system BOOLEAN DEFAULT FALSE,
  can_rename BOOLEAN DEFAULT TRUE,
  can_delete BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  folder_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  link TEXT NOT NULL,
  difficulty ENUM('Easy','Medium','Hard') DEFAULT 'Easy',
  description TEXT,
  code LONGTEXT,
  my_tc VARCHAR(100),
  my_sc VARCHAR(100),
  expected_tc VARCHAR(100),
  expected_sc VARCHAR(100),
  revisit BOOLEAN DEFAULT FALSE,
  revisit_date DATETIME NULL,
  revisit_done BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (folder_id) REFERENCES folders(id) ON DELETE CASCADE
);